# Generated by Django 4.1 on 2024-08-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelClono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('cell_line', models.CharField(max_length=264)),
                ('num_wells', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('analysis_type', models.CharField(choices=[('Single Day', 'Single Day'), ('Multi Day', 'Multi Day')], max_length=50)),
                ('w1_d1_lf', models.FileField(blank=True, null=True, upload_to='downloads\\clono')),
                ('w1_d1_fluo', models.FileField(blank=True, null=True, upload_to='downloads\\clono')),
                ('w2_d1_lf', models.FileField(blank=True, null=True, upload_to='downloads\\clono')),
                ('w2_d1_fluo', models.FileField(blank=True, null=True, upload_to='downloads\\clono')),
                ('w3_d1_lf', models.FileField(blank=True, null=True, upload_to='downloads\\clono')),
                ('w3_d1_fluo', models.FileField(blank=True, null=True, upload_to='downloads\\clono')),
                ('w4_d1_lf', models.FileField(blank=True, null=True, upload_to='downloads\\clono')),
                ('w4_d1_fluo', models.FileField(blank=True, null=True, upload_to='downloads\\clono')),
                ('w1_dn_lf', models.FileField(blank=True, null=True, upload_to='downloads\\clono')),
                ('w1_dn_fluo', models.FileField(blank=True, null=True, upload_to='downloads\\clono')),
                ('w2_dn_lf', models.FileField(blank=True, null=True, upload_to='downloads\\clono')),
                ('w2_dn_fluo', models.FileField(blank=True, null=True, upload_to='downloads\\clono')),
                ('w3_dn_lf', models.FileField(blank=True, null=True, upload_to='downloads\\clono')),
                ('w3_dn_fluo', models.FileField(blank=True, null=True, upload_to='downloads\\clono')),
                ('w4_dn_lf', models.FileField(blank=True, null=True, upload_to='downloads\\clono')),
                ('w4_dn_fluo', models.FileField(blank=True, null=True, upload_to='downloads\\clono')),
            ],
        ),
        migrations.CreateModel(
            name='ModelClonoLabelFree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('cell_line', models.CharField(max_length=264)),
                ('num_wells', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('analysis_type', models.CharField(choices=[('Single Day', 'Single Day'), ('Multi Day', 'Multi Day')], max_length=50)),
                ('w1_d1_lf', models.FileField(blank=True, null=True, upload_to='downloads\\clono')),
                ('w2_d1_lf', models.FileField(blank=True, null=True, upload_to='downloads\\clono')),
                ('w3_d1_lf', models.FileField(blank=True, null=True, upload_to='downloads\\clono')),
                ('w4_d1_lf', models.FileField(blank=True, null=True, upload_to='downloads\\clono')),
                ('w1_dn_lf', models.FileField(blank=True, null=True, upload_to='downloads\\clono')),
                ('w2_dn_lf', models.FileField(blank=True, null=True, upload_to='downloads\\clono')),
                ('w3_dn_lf', models.FileField(blank=True, null=True, upload_to='downloads\\clono')),
                ('w4_dn_lf', models.FileField(blank=True, null=True, upload_to='downloads\\clono')),
            ],
        ),
        migrations.CreateModel(
            name='ModelCountFluo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('cell_line', models.CharField(max_length=264)),
                ('image', models.FileField(upload_to='downloads\\count_fluo')),
            ],
        ),
        migrations.CreateModel(
            name='ModelCountLabelFree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('cell_line', models.CharField(max_length=264)),
                ('image', models.ImageField(upload_to='downloads\\count_labelfree')),
            ],
        ),
    ]
