# Generated by Django 4.1 on 2024-08-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assay_api_app', '0003_alter_modelclono_w1_d1_fluo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcountfluo',
            name='magnification',
            field=models.CharField(default='10x', max_length=20),
        ),
        migrations.AddField(
            model_name='modelcountlabelfree',
            name='magnification',
            field=models.CharField(default='10x', max_length=20),
        ),
    ]
