# Generated by Django 4.1 on 2024-10-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assay_api_app', '0007_alter_modelclono_w1_d1_fluo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelDormancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('cell_line', models.CharField(max_length=264)),
                ('num_wells', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('w1_d1_fluo', models.FileField(blank=True, null=True, upload_to='dormancy_analysis/')),
                ('w2_d1_fluo', models.FileField(blank=True, null=True, upload_to='dormancy_analysis/')),
                ('w3_d1_fluo', models.FileField(blank=True, null=True, upload_to='dormancy_analysis/')),
                ('w4_d1_fluo', models.FileField(blank=True, null=True, upload_to='dormancy_analysis/')),
                ('w1_dn_fluo', models.FileField(blank=True, null=True, upload_to='dormancy_analysis/')),
                ('w2_dn_fluo', models.FileField(blank=True, null=True, upload_to='dormancy_analysis/')),
                ('w3_dn_fluo', models.FileField(blank=True, null=True, upload_to='dormancy_analysis/')),
                ('w4_dn_fluo', models.FileField(blank=True, null=True, upload_to='dormancy_analysis/')),
            ],
        ),
        migrations.CreateModel(
            name='ModelMigration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('cell_line', models.CharField(max_length=264)),
                ('num_wells', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('w1_d1_fluo', models.FileField(blank=True, null=True, upload_to='migration_analysis/')),
                ('w2_d1_fluo', models.FileField(blank=True, null=True, upload_to='migration_analysis/')),
                ('w3_d1_fluo', models.FileField(blank=True, null=True, upload_to='migration_analysis/')),
                ('w4_d1_fluo', models.FileField(blank=True, null=True, upload_to='migration_analysis/')),
                ('w1_dn_fluo', models.FileField(blank=True, null=True, upload_to='migration_analysis/')),
                ('w2_dn_fluo', models.FileField(blank=True, null=True, upload_to='migration_analysis/')),
                ('w3_dn_fluo', models.FileField(blank=True, null=True, upload_to='migration_analysis/')),
                ('w4_dn_fluo', models.FileField(blank=True, null=True, upload_to='migration_analysis/')),
            ],
        ),
    ]
