# Generated by Django 4.1 on 2024-10-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assay_api_app', '0008_modeldormancy_modelmigration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelDormancyLabelFree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('cell_line', models.CharField(max_length=264)),
                ('num_wells', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('w1_d1_fluo', models.FileField(blank=True, null=True, upload_to='dormancy_analysis/labelfree')),
                ('w2_d1_fluo', models.FileField(blank=True, null=True, upload_to='dormancy_analysis/labelfree')),
                ('w3_d1_fluo', models.FileField(blank=True, null=True, upload_to='dormancy_analysis/labelfree')),
                ('w4_d1_fluo', models.FileField(blank=True, null=True, upload_to='dormancy_analysis/labelfree')),
                ('w1_dn_fluo', models.FileField(blank=True, null=True, upload_to='dormancy_analysis/labelfree')),
                ('w2_dn_fluo', models.FileField(blank=True, null=True, upload_to='dormancy_analysis/labelfree')),
                ('w3_dn_fluo', models.FileField(blank=True, null=True, upload_to='dormancy_analysis/labelfree')),
                ('w4_dn_fluo', models.FileField(blank=True, null=True, upload_to='dormancy_analysis/labelfree')),
            ],
        ),
        migrations.RemoveField(
            model_name='modelmigration',
            name='w1_dn_fluo',
        ),
        migrations.RemoveField(
            model_name='modelmigration',
            name='w2_dn_fluo',
        ),
        migrations.RemoveField(
            model_name='modelmigration',
            name='w3_dn_fluo',
        ),
        migrations.RemoveField(
            model_name='modelmigration',
            name='w4_dn_fluo',
        ),
        migrations.AlterField(
            model_name='modeldormancy',
            name='w1_d1_fluo',
            field=models.FileField(blank=True, null=True, upload_to='dormancy_analysis/fluorescent'),
        ),
        migrations.AlterField(
            model_name='modeldormancy',
            name='w1_dn_fluo',
            field=models.FileField(blank=True, null=True, upload_to='dormancy_analysis/fluorescent'),
        ),
        migrations.AlterField(
            model_name='modeldormancy',
            name='w2_d1_fluo',
            field=models.FileField(blank=True, null=True, upload_to='dormancy_analysis/fluorescent'),
        ),
        migrations.AlterField(
            model_name='modeldormancy',
            name='w2_dn_fluo',
            field=models.FileField(blank=True, null=True, upload_to='dormancy_analysis/fluorescent'),
        ),
        migrations.AlterField(
            model_name='modeldormancy',
            name='w3_d1_fluo',
            field=models.FileField(blank=True, null=True, upload_to='dormancy_analysis/fluorescent'),
        ),
        migrations.AlterField(
            model_name='modeldormancy',
            name='w3_dn_fluo',
            field=models.FileField(blank=True, null=True, upload_to='dormancy_analysis/fluorescent'),
        ),
        migrations.AlterField(
            model_name='modeldormancy',
            name='w4_d1_fluo',
            field=models.FileField(blank=True, null=True, upload_to='dormancy_analysis/fluorescent'),
        ),
        migrations.AlterField(
            model_name='modeldormancy',
            name='w4_dn_fluo',
            field=models.FileField(blank=True, null=True, upload_to='dormancy_analysis/fluorescent'),
        ),
    ]
