# Generated by Django 4.1 on 2024-10-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assay_api_app', '0010_rename_w1_d1_fluo_modeldormancylabelfree_w1_d1_lf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeldormancy',
            name='analysis_type',
            field=models.CharField(choices=[('Single Day', 'Single Day'), ('Multi Day', 'Multi Day')], default='Single Day', max_length=50),
        ),
        migrations.AddField(
            model_name='modeldormancylabelfree',
            name='analysis_type',
            field=models.CharField(choices=[('Single Day', 'Single Day'), ('Multi Day', 'Multi Day')], default='Single Day', max_length=50),
        ),
        migrations.AlterField(
            model_name='modelclono',
            name='analysis_type',
            field=models.CharField(choices=[('Single Day', 'Single Day'), ('Multi Day', 'Multi Day')], default='Single Day', max_length=50),
        ),
        migrations.AlterField(
            model_name='modelclonolabelfree',
            name='analysis_type',
            field=models.CharField(choices=[('Single Day', 'Single Day'), ('Multi Day', 'Multi Day')], default='Single Day', max_length=50),
        ),
    ]
