# Generated by Django 4.1 on 2024-10-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assay_api_app', '0011_modeldormancy_analysis_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelclono',
            name='analysis_type',
            field=models.CharField(choices=[('Single Day', 'Single Day'), ('Multi Day', 'Multi Day')], max_length=50),
        ),
        migrations.AlterField(
            model_name='modelclonolabelfree',
            name='analysis_type',
            field=models.CharField(choices=[('Single Day', 'Single Day'), ('Multi Day', 'Multi Day')], max_length=50),
        ),
        migrations.AlterField(
            model_name='modeldormancy',
            name='analysis_type',
            field=models.CharField(choices=[('Single Day', 'Single Day'), ('Multi Day', 'Multi Day')], max_length=50),
        ),
        migrations.AlterField(
            model_name='modeldormancylabelfree',
            name='analysis_type',
            field=models.CharField(choices=[('Single Day', 'Single Day'), ('Multi Day', 'Multi Day')], max_length=50),
        ),
    ]
