# Generated by Django 4.1 on 2024-10-30 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assay_api_app', '0014_alter_modelclono_magnification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelmigration',
            old_name='w1_d1_fluo',
            new_name='w1_fluo',
        ),
        migrations.RenameField(
            model_name='modelmigration',
            old_name='w2_d1_fluo',
            new_name='w2_fluo',
        ),
        migrations.RenameField(
            model_name='modelmigration',
            old_name='w3_d1_fluo',
            new_name='w3_fluo',
        ),
        migrations.RenameField(
            model_name='modelmigration',
            old_name='w4_d1_fluo',
            new_name='w4_fluo',
        ),
    ]
